#Reference: http://wiki.ros.org/navigation/Tutorials/RobotSetup
#The first section of parameters above define the velocity limits of the robot. 
#The second section defines the acceleration limits of the robot.

TrajectoryPlannerROS:
  max_vel_x: 3.0
  min_vel_x: -3.0
  max_vel_theta: 2.0
  min_in_place_vel_theta: 0.7

  acc_lim_theta: 0.7
  acc_lim_x: 0.75
  acc_lim_y: 0.75

  holonomic_robot: false 
