#Reference: http://wiki.ros.org/navigation/Tutorials/RobotSetup
#"global_frame" parameter defines what coordinate frame the costmap should run in, in this case, we'll choose the /map frame.
#"robot_base_frame" parameter defines the coordinate frame the costmap should reference for the base of the robot.
#"update_frequency" parameter determines the frequency, in Hz, at which the costmap will run its update loop.
#"static_map" parameter determines whether or not the costmap should initialize itself based on a map served by the map_server. If you aren't using an existing map or map server, set the static_map parameter to false.

global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true