<?xml version="1.0"?>

<!-- TODO medir parametros inerciais reais -->
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">  

	<material name="gray">
  		<color rgba="0.5 0.5 0.5 1"/>
  	</material>

	<material name="white">
  		<color rgba="1 1 1 1"/>
  	</material>

	<!-- Chutado -->
	<xacro:property name="CHASSI_MASS" value="1.0"/>

	<!-- Medidos --> 
	<xacro:property name="CHASSI_RADIUS" value="0.28"/>
	<xacro:property name="CHASSI_THICKNESS" value="0.0155"/>

	<!-- Virtual base as recommended -->
	<link name="base_link"/>

	<!-- Real base, named as chassi -->
	<link name="chassi_link">

			<visual>
					<material name="green">
						<color rgba="0.2 1 0.2 1"/>
					</material>
					<geometry>	
							<cylinder length="${CHASSI_THICKNESS}" radius="${CHASSI_RADIUS}" />
					</geometry>

					<origin xyz="0 0 0" rpy="0 0 0" />
					<material name="white"/>
			</visual>

			<collision>
					<geometry>
						<cylinder length="${CHASSI_THICKNESS}" radius="${CHASSI_RADIUS}"/>
					</geometry>

					<origin xyz="0 0 0" rpy="0 0 0" />
			</collision>

			<inertial>
					<mass value="${CHASSI_MASS}"/>

					<!-- Centro de massa -->
					<origin xyz="0 0 0" rpy="0 0 0"/>
					<inertia
							ixx="${(1/12) * CHASSI_MASS * (3 * CHASSI_RADIUS * CHASSI_RADIUS + CHASSI_THICKNESS * CHASSI_THICKNESS)}" ixy="0" ixz="0"
							iyy="${(1/12) * CHASSI_MASS * (3 * CHASSI_RADIUS * CHASSI_RADIUS + CHASSI_THICKNESS * CHASSI_THICKNESS)}" iyz="0"
							izz="${(1/2) * CHASSI_MASS * CHASSI_RADIUS * CHASSI_RADIUS}"/>
			</inertial>
	</link>
	
	<!-- Chutado -->                                      		
    <xacro:property name="SUPPORT_MASS" value="0.5"/>
	                                                       
    <!-- Medidos --> 
    <xacro:property name="SUPPORT_RADIUS" value="0.019"/>
    <xacro:property name="SUPPORT_THICKNESS" value="1.25"/>

	<link name="vertical_support_link">

			<visual>
				<geometry>
						<cylinder length="${SUPPORT_THICKNESS}" radius="${SUPPORT_RADIUS}"/>
				</geometry>

				<origin xyz="0 0 ${(1/2) * SUPPORT_THICKNESS}" rpy="0 0 0"/>

				<material name="gray"/>
			</visual>

			<collision>
				<geometry>                                                                  	
            			<cylinder length="${SUPPORT_THICKNESS}" radius="${SUPPORT_RADIUS}"/>
            	</geometry>
                                                                                             
            	<origin xyz="0 0 ${(1/2) * SUPPORT_THICKNESS}" rpy="0 0 0"/>
			</collision>

			<inertial>
					<mass value="${SUPPORT_MASS}"/>

					<origin xyz="0 0 0" rpy="0 0 0"/>

					<inertia
                    		ixx="${(1/12) * SUPPORT_MASS * (3 * SUPPORT_RADIUS * SUPPORT_RADIUS +SUPPORT_THICKNESS * SUPPORT_THICKNESS)}" ixy="0" ixz="0"
                    		iyy="${(1/12) * SUPPORT_MASS * (3 * SUPPORT_RADIUS * SUPPORT_RADIUS + SUPPORT_THICKNESS * SUPPORT_THICKNESS)}" iyz="0"
                    		izz="${(1/2) * SUPPORT_MASS * SUPPORT_RADIUS * SUPPORT_RADIUS}"/>

			</inertial>
	</link>
	
</robot>
