<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
			
		<!-- Joint to connect lidar to base 
        <joint name="base_lidar_joint" type="fixed">

            <parent link="base_link"/>
            <child link="lidar"/>

            <origin xyz="" rpy=""/>

		</joint> -->

		<joint name="base_support_joint" type="fixed">

				<parent link="base_link"/>
				<child link="vertical_support_link"/>

				<origin xyz="0.205 0 ${(1/2)*BASE_THICKNESS + 0.05}" rpy="0 0 0"/>

		</joint>

</robot>
