<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<material name="black">
		<color rgba="0 0 0 1"/>
	</material> 

	<!-- Wheel Properties -->
	<xacro:property name="WHEEL_THICKNESS" value="0.051" />
	<xacro:property name="WHEEL_RADIUS" value="0.08" />

	<!-- Chutado -->
	<xacro:property name="WHEEL_MASS" value="1" />

	<xacro:macro name="wheel_link" params="position_prefix">

		<link name="${position_prefix}_wheel_link">

			<visual>

				<geometry>
					<cylinder length="${WHEEL_THICKNESS}" radius="${WHEEL_RADIUS}" />
				</geometry>
				<!-- 
				<origin xyz="0 0 ${(1/2)*WHEEL_THICKNESS}" rpy="0 0 0" /> 
				-->
				<origin xyz="0 0 0" rpy="0 0 0" />
				<material name="black" />

			</visual>

			<collision>

				<geometry>
					<cylinder length="${WHEEL_THICKNESS}" radius="${WHEEL_RADIUS}" />
				</geometry>
				<origin xyz="0 0 0" rpy="0 0 0" />

			</collision>

			<inertial>
				<mass value="${WHEEL_MASS}" />

				<!-- Centro de massa -->
				<origin xyz="0 0 0" rpy="0 0 0" />
				<inertia ixx="${(1/12) * WHEEL_MASS * (3 * WHEEL_RADIUS * WHEEL_RADIUS + WHEEL_THICKNESS * WHEEL_THICKNESS)}" ixy="0" ixz="0" iyy="${(1/12) * WHEEL_MASS * (3 * WHEEL_RADIUS * WHEEL_RADIUS + WHEEL_THICKNESS * WHEEL_THICKNESS)}" iyz="0" izz="${(1/2) * WHEEL_MASS * WHEEL_RADIUS * WHEEL_RADIUS}" />
			</inertial>

		</link>
	</xacro:macro>

	<xacro:wheel_link position_prefix="left" />
	<xacro:wheel_link position_prefix="right" />

</robot>